# Slicing A Matrix

Based on [http://www.amazon.com/Python-Probability-Statistics-Machine-Learning/dp/3319307150](Python for Probability, Statistics, and Machine Learning) by José Unpingco.

## Preliminaries

In [1]:
# Import Numpy
import numpy as np

## Create a matrix

In [19]:
# Create a variable called 'matrix' that is a 2 by 3 matrix
matrix = np.matrix([[1,2,3], [4,5,6]])

In [20]:
# View the matrix
matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

## Slice the matrix

In [21]:
# View only the first row (and all columns) of the matrix
matrix[0,:]

matrix([[1, 2, 3]])

In [22]:
# View only the second column (and all the rows) of the matrix
matrix[:,1]

matrix([[2],
        [5]])

In [23]:
# View every other column (and all rows) of the matrix

In [24]:
matrix[:,::2]

matrix([[1, 3],
        [4, 6]])